apm install project-manager
apt install language-cython
apm install language-docker
apm install language-salt
apm install atom-jinja2
apm install highlight-selected
apm install vim-mode
apm install pretty-json
apm install less-compiler
apm install tabs-to-spaces
apm install auto-detect-indentation
apm install linter-flake8
apm install python-tools
