apm install project-manager
apm install linter
apm install linter-pylint
apm install highlight-selected
apt install language-cython
apm install language-docker
apm install less-compiler
apm install language-salt
apm install atom-jinja2
apm install tabs-to-spaces
apm install auto-detect-indentation
